# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-06 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DartName', models.CharField(max_length=100)),
                ('DartValue', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DartPlayed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumberOfDart', models.IntegerField()),
                ('Turn', models.IntegerField()),
                ('Dart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darts.Dart')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayerName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ScoreTotal', models.IntegerField(default=0)),
                ('Score1', models.IntegerField(default=3)),
                ('Score2', models.IntegerField(default=3)),
                ('Score3', models.IntegerField(default=3)),
                ('Score4', models.IntegerField(default=3)),
                ('Score5', models.IntegerField(default=3)),
                ('Score6', models.IntegerField(default=3)),
                ('Score7', models.IntegerField(default=3)),
                ('Game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darts.Game')),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darts.Player')),
            ],
        ),
        migrations.CreateModel(
            name='RefGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GameName', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='RefGame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darts.RefGame'),
        ),
        migrations.AddField(
            model_name='dartplayed',
            name='Game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darts.Game'),
        ),
        migrations.AddField(
            model_name='dartplayed',
            name='Player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darts.Player'),
        ),
    ]
