# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-04 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LnkDartPlayedScoreUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DartTurn', models.IntegerField()),
                ('ScoreName', models.CharField(max_length=6)),
                ('ScoreValue', models.IntegerField()),
                ('DartPlayed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darts.LnkGamePlayerDartPlayed')),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darts.Player')),
            ],
        ),
        migrations.RemoveField(
            model_name='lnkgameplayerscore',
            name='LastScore',
        ),
    ]
