# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-05 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0003_lnkgameplayerdartplayed_turndart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lnkdartplayedscoreupdate',
            name='DartTurn',
        ),
    ]
